export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_SONG_QUEUE = 'SET_SONG_QUEUE';

export const GET_RELATED_SONGS_START = 'GET_RELATED_SONGS_START';
export const GET_RELATED_SONGS_SUCCESS = 'GET_RELATED_SONGS_SUCCESS';
