export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const ADD_NEW_PLAYLIST = 'ADD_NEW_PLAYLIST';

export const SET_SONG_DOWNLADING = 'SET_SONG_DOWNLADING';
export const ADD_SONG_TO_DOWNLOADS = 'ADD_SONG_TO_DOWNLOADS';
export const REMOVE_SONG_FROM_DOWNLOADS = 'REMOVE_SONG_FROM_DOWNLOADS';

export const FAVOURITE_ID = 22;
export const DOWNLOAD_ID = 23;
