export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_SONG_LOADING = 'SET_SONG_LOADING';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_SEEK_POSITION = 'SET_SEEK_POSITION';
export const TOGGLE_SONG_FAVOURITE = 'TOGGLE_SONG_FAVOURITE';
