name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  # run-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install npm dependencies
  #       run: |
  #         npm install
  build-debug-android:
    # needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build debug apk
        run: |
          npm run buildDebug
      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
